language: generic
os: osx
osx_image: xcode8.3
before_install:
  - export VERSION=${TRAVIS_TAG:-snapshot}
  - brew update
  - brew tap homebrew/homebrew-php
  - brew install php72 php72-xdebug
script:
  - mkdir bundle && cd bundle
  - cp ../php.sh . && chmod +x php.sh
  - ln -s /usr/local/Cellar/php /usr/local/Cellar/php72
  - cp -r /usr/local/Cellar/php72/$(brew list --versions php72 | awk '{print $2;}') php72
  - cp -r /usr/local/Cellar/php72-xdebug/$(ls /usr/local/Cellar/php72-xdebug/) php72-xdebug
  - mkdir lib
  - cp /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib lib
  - cp /usr/local/opt/openssl/lib/libssl.1.0.0.dylib lib
  - cp /usr/local/opt/readline/lib/libreadline.7.dylib lib
  - cp /usr/local/opt/gettext/lib/libintl.8.dylib lib
  - cp /usr/local/opt/libxml2/lib/libxml2.2.dylib lib
  - cp /usr/local/opt/freetype/lib/libfreetype.6.dylib lib
  - cp /usr/local/opt/jpeg/lib/libjpeg.9.dylib lib
  - cp /usr/local/opt/unixodbc/lib/libodbc.2.dylib lib
  - cp /usr/local/opt/libpng/lib/libpng16.16.dylib lib
  - cp /usr/local/opt/libtool/lib/libltdl.7.dylib lib
  - cp /usr/local/opt/libsodium/lib/libsodium.23.dylib lib
  - cp /usr/local/opt/libzip/lib/libzip.5.dylib lib
  - cp /usr/local/opt/argon2/lib/libargon2.1.dylib lib
  - cp /usr/local/opt/aspell/lib/libaspell.15.dylib lib
  - cp /usr/local/opt/aspell/lib/libpspell.15.dylib lib
  - cp /usr/local/opt/freetds/lib/libsybdb.5.dylib lib
  - cp /usr/local/opt/gmp/lib/libgmp.10.dylib lib
  - cp /usr/local/opt/webp/lib/libwebp.7.dylib lib
  - cp /usr/local/opt/icu4c/lib/libicui18n.60.dylib lib
  - cp /usr/local/opt/icu4c/lib/libicuuc.60.dylib lib
  - cp /usr/local/opt/icu4c/lib/libicudata.60.2.dylib lib
  - cp /usr/local/opt/icu4c/lib/libicuio.60.dylib lib
  - cp /usr/local/opt/icu4c/lib/libicudata.60.dylib lib
  - mkdir ini
  - cp /usr/local/etc/php/7.2/php.ini ini
  - cp -r /usr/local/etc/php/7.2/conf.d ini
  - sed -i '' "s=/usr/local/opt/php72-xdebug/xdebug.so=\$(pwd)/php72-xdebug/xdebug.so=g" $(pwd)/ini/conf.d/ext-xdebug.ini
  - tar czf ../php72-${VERSION}.tar.gz .
  - sed -i '' "s=\$(pwd)/php72-xdebug/xdebug.so=$(pwd)/php72-xdebug/xdebug.so=g" $(pwd)/ini/conf.d/ext-xdebug.ini
  - brew rm --ignore-dependencies php72 php72-xdebug $(brew deps php72)
  - ./php.sh --version
  - ./php.sh --ini
  - brew install openssl gmp
  - cd ..
deploy:
  provider: releases
  api_key:
    secure: BJpnmALcNUjawlDKn0HFp5nuitSvzYVzj0WkR5CjOuEhA04PWv4l1IwAQSU+HfpPI3pnf4QONpk9lkYNpHHCszYx17oiiMo8axysxls1/RUWhv2MJOZDx55Bh7oe1BtCRfwO9SSCdldjkTkUz0goxnm3fXPy2cCm9t63MZexLlLsER18mY8qptragC1vhPmq4pPTc3sUMZwU/ZX4maydQaeT2Npt12Bt0TFSxMnmc2HwC2HiYjVIfcennoObxHXAhZY1xftJErl3YEjBY87xRY0tsZxXvF9Di+zE840Cx+WVSjMhl+kh5w1d1zaa4P3XYiErFqq/xdBn2hpwcRhc6YTQQ3B8M0kIP1UHLmER+0neiuOOPedCMgTlYA0unbQWCELlMzc00cCpEuyyCIneaw1cGnAagjYrG5EM82aXeG9SJKI2jVa1I2+mykFMVmg80wlDDQLTuC6rkaxIIAg7XurL6pp7BTYcfVBsbyXt1k86qWtkvBDs8vtluI5SR5bL6jfdIAcu3g3k98K5nh03J5+Z0IUHmmgo0Joo3R7hLvuq1ZI5ygJNIxcKpU7X/6K3OcNz1blphLWq1CdJCFXl450i5FwiDH2tC1+macUGDk6QNnabsm1kMfJkziVlsV8K1ZusI8bAU6KP1KRtojy/sWO2c1RhSSo9ml5e7nEDrI4=
  file: php72-${VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
